### ISSUE TITLE
Unable to login to test event or site

### ISSUE THREAD

**Issue by jeffguy1** [undyau/meos-oz#20]
Hi,

I am testing the new version of Meos-oz. 

I am unable to login to the test Eventor site to setup a test event so I can test Meos-oz. could you give me access please?

Regards,
Jeff

**Comment by undyau** [comment]
Hi Jeff

It should just be your usual name/password. I can't reset your password
because I only have access to bigfoot members. Onsw admin (John) may be
able to do it.

Andy

**Comment by jeffguy1** [comment]
Ok, thanks.  I'll contact John.

Jeff

**Comment by undyau** [comment]
Assume solved, Jeff now testing something else.
