### ISSUE TITLE
Rogaining event issue after import

### ISSUE THREAD

**Issue by mkozma** [undyau/meos-oz#45]
We have found the issue in MEOS-OZ but have posted the issue to the main development branch:
https://github.com/melinsoftware/meos/issues/55

Not sure if it is required in both places.

Regards,
Martin Kozma
Bayside Kangaroos Orienteering Club

**Comment by undyau** [comment]
> We have found the issue in MEOS-OZ but have posted the issue to the main development branch: [melinsoftware/meos#55](https://github.com/melinsoftware/meos/issues/55)
> 
> Not sure if it is required in both places.
> 
> Regards, Martin Kozma Bayside Kangaroos Orienteering Club

Hi Martin,

I'm happy to look at this. Please could you send the problem file - I couldn't recreate it.

Kind Regards,
Andy

**Comment by mkozma** [comment]
Thanks Andy,
Here is the backup file and some screenshots.
[MeosIssue45.zip](https://github.com/undyau/meos-oz/files/11077526/MeosIssue45.zip)

Regards,
Martin

**Comment by undyau** [comment]
Hi Martin,

It looks as though you may have done something funky when initially configuring that class - maybe around start times or legs ?

In the backup file there are a couple of lines that relate to that and they are causing MeOS to think that the ADRF class has a pool of courses (albeit size 1) associated with it.

If that sounds kind of familiar then it is probably the underlying cause - I don't think that you will see that issue again.

If you did deliberately do something about start times for this class, then now that the results are done, I can't see what you were trying to do. If you let me know I may be able to reproduce.

**Comment by mkozma** [comment]
Thanks Andy. 
You're right. I was playing around with start lists and had some start times in there.
Removing this fixed the issue.
Please resolve the issue.
Cheers,
Martin
