### ISSUE TITLE
Prevent hang when running custom list

### ISSUE THREAD

**Issue by undyau** [undyau/meos-oz#50]
When trying to print the attached custom list MeOS crashed.
[StartTime.zip](https://github.com/user-attachments/files/16846342/StartTime.zip)

**Comment by undyau** [comment]
Can't reproduce when running standalone.

**Comment by mkozma** [comment]
I have a similar issue but can't quite track down the use case. It is in the main branch of the software as well and for standard AND custom lists and only on site. I suspect it has something to do with bringing up the printer dialog window, At events, it is always an Epson Receipt printer.

**Comment by undyau** [comment]
Looks as though this also occurred with MeOS 3.8 software. 
Will test on Windows 10 - I don't recognise the problematic printer dialog. It seems to behave non-modally in that after it has hung meos, when you shoot down meos instance, the dialog persists.

**Comment by mkozma** [comment]
We first encountered this in the Prize Money Ceremony report, which is not a custom list. We have setup where we have 8 services running (for displaying results to tvs), so we're not sure if that is related or not. The problem is, we have to recreate all the services after the crash. The other thing I didn't try, was print to PDF, as this would bypass the print modal.

**Comment by undyau** [comment]
I think that I have a workaround. It seems that the problem is associated with the new Printer Selection dialog - so in an older Win 10 environment, everything was fine.

It is possible to force use of the old dialog in Win 11 - see [here](https://wiki.autocountsoft.com/wiki/Others:_How_to_switch_back_to_the_old_print_dialog_in_Windows_11%3F). I did that and the problem seems to be fixed.

Not very elegant, but it should work for you as a workaround (I will go and apply this on my club's laptops).

**Comment by undyau** [comment]
It is possible to force use of the old printer selection dialog in code by setting PRINTDIALOG's `hwndOwner` attribute to `NULL`. This means that the registry workaround isn't required.

This change has been made (will be in next release). 
Will add some detail in upstream MeOS GitHub.
